# version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: runner_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: runner
    ports:
      - "5432:5432"
    tmpfs:                                      // for temporary memory storage
      - /var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: runner_queue
    ports:
      - "6379:6379"